services:
  - type: web
    name: od-api
    env: python
    plan: free
    rootDir: api
    buildCommand: |
      pip install -U pip
      pip install -r requirements.txt
    startCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: od-postgres
          property: connectionString
      - key: CORS_ORIGIN
        value: https://operationaldashboard.vercel.app,https://*.vercel.app
      - key: PYTHONPATH
        value: .
    autoDeploy: true
