# render.yaml
services:
  - type: web
    name: od-api
    env: python
    plan: free
    rootDir: api
    buildCommand: |
      pip install -U pip
      if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # If you use pyproject.toml with poetry/pdm/etc, swap the line above accordingly.
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: od-postgres
          property: connectionString
      - key: CORS_ORIGIN
        value: https://operationaldashboard.vercel.app
      - key: PYTHONPATH
        value: .
      # If your SQLAlchemy driver needs it, Render’s Postgres often wants SSL:
      # - key: SQLALCHEMY_DATABASE_URI
      #   value: ${DATABASE_URL}?sslmode=require
    autoDeploy: true

databases:
  - name: od-postgres
    plan: free
