# render.yaml
services:
  - type: web
    name: od-api
    env: python
    plan: free
    rootDir: api
    buildCommand: |
      pip install -U pip
      # if you have requirements.txt in api/, this is perfect:
      if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      # if you ONLY have pyproject.toml, do:
      if [ -f pyproject.toml ]; then pip install -e .; fi
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: od-postgres
          property: connectionString
      - key: CORS_ORIGIN
        value: https://operationaldashboard.vercel.app/
      - key: PYTHONPATH
        value: .
    autoDeploy: true
    # run once on first deploy (creates tables)
    postDeployCommand: |
      python - <<'PY'
      from app.db import engine
      from app.models import Base
      Base.metadata.create_all(bind=engine)
      print("ok: tables created")
      PY

databases:
  - name: od-postgres
    plan: free
